server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/week?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC

mybatis:
  type-aliases-package: com.qfedu.pojo
  mapper-locations: classpath:mapper/*Mapper.xml
